"""empty message

Revision ID: e542771a64cb
Revises: 42233d18ac7b
Create Date: 2018-04-11 03:40:56.407866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e542771a64cb'
down_revision = '42233d18ac7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dept_pref', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'departments', ['dept_pref'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'dept_pref')
    # ### end Alembic commands ###
